### PR TITLE
Update the stable-diffusion test model

### PR DESCRIPTION
**Pull request by daniandtheweb**
I've found an archive of the original stable diffusion 1.5 model that doesn't require any login.
The original upload made by Stability-AI has been removed so the archive made by the ComfyUI team seems the best place to download it from.

### CODE REVIEW

**Comment by lamikr** [comment]
Thanks, I will update this. Btw. I looked it more briefly the stable-diffusion-cpp and as it was CMake based project I made 2 small changes to stable-diffusion-cpp.binfo file. 

1) I specified the rocm sdk builder root directory as a install target
(BINFO_APP_CMAKE_CFG="-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR_PREFIX_SDK_ROOT}")
2) I removed the "BINFO_APP_INSTALL_CMD_ARRAY=(" because rocm sdk builder will by default call
    "make install" if that is not specified. Now the make install did the same "cp" that you did + it also installed the
   stable diffusion cpp libraries and headers.

That may help you if you build your own ui that depends those the stable diffusion cpp files.

**Comment by daniandtheweb** [comment]
I used the copy method because I wasn't able to make it install with the default call but I guess I've just misconfigured the binfo.

**Comment by daniandtheweb** [comment]
@lamikr I've actually just checked your changes to the build of stable-diffusion.cpp and I've found out the same issue I've been having before.

```
-- Install configuration: "Release"
CMake Error at ggml/cmake_install.cmake:51 (file):
  file cannot create directory: /usr/local/lib64.  Maybe need administrative
  privileges.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)
``` 
I think a patch should be required to install it correctly with the default install method as it currently tries to install the files in /usr/local/lib64.

**Comment by lamikr** [comment]
Yes, it was propably that the target directory needed to be specified also on configure, otherwise it would have tried to install it by default under /usr/local. Possible problems you have are good information as the binfo files should be documented also. Now all I have are just a real binfo files that one needs to check to find examples.

Do you think it would be possible for you to use the latest version of upstream ggml files instead?

Alternatively we could install them for your case to subproject like /opt/rocm_sdk_612/apps/stable-diffusion-cpp?
(I already ended up doing that kind of approach for stable-diffusion-webui because it was somekind behaving differently compared to traditional other apps and required a big set of own custom directories and that's why I felt that that it was just more clear to install it completely separate directory.)

I merge this now, let's continue discussion under some other topic.

**Pull request merged**
