### PR TITLE
add more rocm development and tracing tools

### PR DESCRIPTION
**Pull request by lamikr**
- amdsmi
- rocdbgapi
- rocgdb
- nvtop

### CODE REVIEW

**Comment by lamikr** [comment]
https://github.com/lamikr/rocm_sdk_builder/issues/106

**Comment by daniandtheweb** [comment]
For arch the dependencies would be `ncurses`, `expat`, `babeltrace` and `systemd` (I'm not sure if it's worth adding as systemd is installed by default in arch). 

I'm unable to build amdsmi.
```
[ 13%] Building CXX object src/CMakeFiles/amd_smi.dir/amd_smi/amd_smi_lib_loader.cc.o
cd /home/daniandtheweb/WorkSpace/rocm_sdk_builder/builddir/013_02_amdsmi/src && /usr/bin/c++ -DENABLE_ESMI_LIB=1 -Damd_smi_EXPORTS -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/third_party/shared_mutex -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include -I/usr/include/libdrm -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/include -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/common/shared_mutex -I/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/include -Wtrampolines -Wl,-z,now -Wall -Wextra -fno-rtti -m64 -msse -msse2 -Wconversion -Wcast-align -Wformat=2 -fno-common -Wstrict-overflow -Woverloaded-virtual -Wreorder -Wno-write-strings -O3 -DNDEBUG -std=c++17 -fPIC -MD -MT src/CMakeFiles/amd_smi.dir/amd_smi/amd_smi_lib_loader.cc.o -MF CMakeFiles/amd_smi.dir/amd_smi/amd_smi_lib_loader.cc.o.d -o CMakeFiles/amd_smi.dir/amd_smi/amd_smi_lib_loader.cc.o -c /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/amd_smi/amd_smi_lib_loader.cc
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc: In function ‘rsmi_status_t rsmi_dev_pci_bandwidth_get(uint32_t, rsmi_pcie_bandwidth_t*)’:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc:2938:19: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
 2938 |   if (width_index == -1 || speed_index == -1) {
      |       ~~~~~~~~~~~~^~~~~
In file included from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/amdsmi.h:57:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h: At global scope:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h:22:20: warning: ‘bw_string’ defined but not used [-Wunused-variable]
   22 | static const char *bw_string[3] = {"aggregate", "read", "write"}; //!< bandwidth types for io/xgmi links
      |                    ^~~~~~~~~
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc:2938:40: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
 2938 |   if (width_index == -1 || speed_index == -1) {
      |                            ~~~~~~~~~~~~^~~~~
make[2]: *** [src/CMakeFiles/amd_smi.dir/build.make:79: src/CMakeFiles/amd_smi.dir/amd_smi/amd_smi.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc: In function ‘rsmi_status_t rsmi_dev_cache_info_get(uint32_t, rsmi_gpu_cache_info_t*)’:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc:3868:17: warning: unused variable ‘ret’ -Wunused-variable]
 3868 |   rsmi_status_t ret;
      |                 ^~~
In file included from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/amd_smi/amd_smi_gpu_device.cc:48:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/include/rocm_smi/rocm_smi_utils.h: In member function ‘amd::smi::ScopeGuard<lambda>& amd::smi::ScopeGuard<lambda>::operator=(const amd::smi::ScopeGuard<lambda>&)’:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/include/rocm_smi/rocm_smi_utils.h:224:18: error: assignment of member ‘dismiss_’ in read-only object
  224 |     rhs.dismiss_ = true;
      |     ~~~~~~~~~~~~~^~~~~~
make[2]: *** [rocm_smi/CMakeFiles/rocm_smi64.dir/build.make:107: rocm_smi/CMakeFiles/rocm_smi64.dir/src/rocm_smi_device.cc.o] Error 1
In file included from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/amdsmi.h:57,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/impl/amd_smi_lib_loader.h:2,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/amd_smi/amd_smi_lib_loader.cc:44:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h:22:20: warning: ‘bw_string’ defined but not used [-Wunused-variable]
   22 | static const char *bw_string[3] = {"aggregate", "read", "write"}; //!< bandwidth types for io/xgmi links
      |                    ^~~~~~~~~
In file included from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/amdsmi.h:57,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/impl/amd_smi_gpu_device.h:4,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/amd_smi/amd_smi_gpu_device.cc:44:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h: At global scope:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h:22:20: warning: ‘bw_string’ defined but not used [-Wunused-variable]
   22 | static const char *bw_string[3] = {"aggregate", "read", "write"}; //!< bandwidth types for io/xgmi links
      |                    ^~~~~~~~~
make[2]: *** [src/CMakeFiles/amd_smi.dir/build.make:121: src/CMakeFiles/amd_smi.dir/amd_smi/amd_smi_gpu_device.cc.o] Error 1
In file included from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/amdsmi.h:57,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/include/amd_smi/impl/amd_smi_drm.h:52,
                 from /home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/src/amd_smi/amd_smi_drm.cc:50:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h: At global scope:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/esmi_ib_library/include/e_smi/e_smi.h:22:20: warning: ‘bw_string’ defined but not used [-Wunused-variable]
   22 | static const char *bw_string[3] = {"aggregate", "read", "write"}; //!< bandwidth types for io/xgmi links
      |                    ^~~~~~~~~
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc: At global scope:
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc:1677:13: warning: ‘void get_vc_region(uint32_t, std::vector<std::__cxx11::basic_string<char> >*, rsmi_freq_volt_region_t*)’ defined but not used [-Wunused-function]
 1677 | static void get_vc_region(uint32_t start_ind,
      |             ^~~~~~~~~~~~~
/home/daniandtheweb/WorkSpace/rocm_sdk_builder/src_projects/amdsmi/rocm_smi/src/rocm_smi.cc:210:13: warning: ‘void freq_volt_string_to_point(std::string, rsmi_od_vddc_point_t*)’ defined but not used [-Wunused-function]
  210 | static void freq_volt_string_to_point(std::string in_line,
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [rocm_smi/CMakeFiles/rocm_smi64.dir/build.make:79: rocm_smi/CMakeFiles/rocm_smi64.dir/src/rocm_smi.cc.o] Error 1
make[2]: Leaving directory '/home/daniandtheweb/WorkSpace/rocm_sdk_builder/builddir/013_02_amdsmi'
make[1]: *** [CMakeFiles/Makefile2:210: rocm_smi/CMakeFiles/rocm_smi64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/daniandtheweb/WorkSpace/rocm_sdk_builder/builddir/013_02_amdsmi'
make[1]: *** [CMakeFiles/Makefile2:262: src/CMakeFiles/amd_smi.dir/all] Error 2
make[1]: Leaving directory '/home/daniandtheweb/WorkSpace/rocm_sdk_builder/builddir/013_02_amdsmi'
make: *** [Makefile:159: all] Error 2
build failed: amdsmi
Failed to build ROCM_SDK_BUILDER
```

**Comment by jeroen-mostert** [comment]
`systemd` is a *really* suspect dependency. This shouldn't be installed if it's not already, since people who choose not to have `systemd` would usually have a strong reason. Best I can imagine is that some of these things either require libraries to communicate with `systemd` if it's installed, or else they want to install service files by default -- neither of which ought to require a complete `systemd`.

**Comment by lamikr** [comment]
@daniandtheweb Thanks, I had forgotten to add the amdsmi patch, the same error showed up also on fedora 40.
I have now pushed the fix, if you can pull it you need to now apply patches.  I also updated the dependencies list with those you said.

./babs.sh -co
./babs.sh -ap
./babs.sh -b

**Pull request merged**
