### PR TITLE
stable-diffusion.cpp binfo

### PR DESCRIPTION
**Pull request by daniandtheweb**
I've currently just created the binfo for stable-diffusion.cpp.
@lamikr  Does it look good? I'm not sure about the installation process.

Later I'll create also the binfo for my webui. Is there any way to set stable-diffusion.cpp as a dependency? I'd like to just create a symlink that points to the sd executable so that no further patches are needed.

### CODE REVIEW

**Comment by lamikr** [comment]
It looks, I will try to build and test it out. Do you have any instructions how to test it?

**Comment by daniandtheweb** [comment]
stable-diffusion.cpp loads the same safetensors files that any other stable diffusion does so an example test command could be something like this:
```
sd -M txt2img -p "a cat" -m /opt/rocm_sdk_models/safetensors_model.safetensors
``` 
The output, if no specific option is specified, gets saved in the current directory of the terminal as output.png.

**Comment by lamikr** [comment]
Thanks, I tested it and build and works great. I could merge it even now if you want? Or if you want to include some doc to README.md and add it also to binfo/extra/ai_tools.blist?

Maybe something like this could be added to README.md before the stable-diffusion-webui example for own stable-diffusion-cpp:

./babs.sh -b binfo/extra/stable-diffusion_cpp.binfo
cd /opt/rocm_sdk_models
curl -L -O https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/resolve/main/sd-v1-4.ckpt
source /opt/rocm_sdk_612/bin/env_rocm.sh
sd -M txt2img -p "a cat" -m /opt/rocm_sdk_models/sd-v1-4.ckpt -o cat.png
eog cat.png

Model is pretty old but I prefer advising some model which does not require authenitcating in documentation, not sure what would be best in that sense. We could merge this first as it's own and then do a second pr for your ui.
And we could add this line to binfo/core/ai_tools.blist

binfo/core/ai_tools.blist could be like this.

binfo/extra/ai_tools_dependencies.binfo
binfo/extra/vllm.binfo
binfo/extra/stable-diffusion_cpp.binfo
binfo/extra/stable-diffusion-webui.binfo
binfo/extra/llama_cpp.binfo

**Comment by daniandtheweb** [comment]
Ok, I'll let the webui commit for a different pr.
I think this should be ready for merging. I'll take a look if there are any models similar to 1.5 that don't require any authentication to download since 1.4 is quite old and the quality upgrade to 1.5 is huge.

**Comment by lamikr** [comment]
This looks good, It's nice to get stable-diffusion-cpp included.

**Pull request merged**
