### PR TITLE
Refactor to make the babs.sh more mantainable.

### PR DESCRIPTION
**Pull request by JassonCordones**
This pull request refactors the monolithic babs.sh script into several smaller, more focused files. The refactoring aims to improve code organization, readability, and maintainability. The main changes include:

1. Splitting functions into logical groups
2. Creating separate files for different areas of functionality
3. Improving overall code structure

The refactoring does not change any existing functionality but sets the groundwork for easier future development and maintenance of the babs build system.

### CODE REVIEW

**Comment by lamikr** [comment]
I like the idea of doing little bit re-structuring for the files, especially as some new functionality for handling the git clone/build/install for single files is in ./build/build_func.sh while some of the older code for fetching all files, etc.. is in babs.sh

I would however like to avoid creating the helpers directory righ in the root. Maybe just use the build-directory also for new files? And I would like to get these things addressed while doing the refactoring:

  1) https://github.com/lamikr/rocm_sdk_builder/issues/110
  2) reset command (-re?) which would do both the -co and -ap. 
  3) If checkout command fails because git does not have the revision to checkout, it should do the fetch and then try again for that repo.

**Comment by JassonCordones** [comment]
Thanks for the feedback. I was also debating if creating a new directory was a good idea, but I was not sure where it made sense to put the new files. I'll probably use the build dir as you suggest. 

I wouldn't know how to categorize the packages to create the additional list you mention in #110. 
I'll try to check if I can address the rest of the points you mention when I get some spare time.

**Comment by lamikr** [comment]
In ideal world the babs.sh + files in build dir would be generic and could be used also on building something totally different and files in binfo would then define all the environment variables and what to build. The idea is kind of there but there are propably something hardcoded that would only be detected when really trying to build different things. But I think it's better to do that kind of final cleaning later. But if you could get the list-support added, that would be very good addition for now.

Good test case could be to create binfo/ai_tools.blist file which could contains for example 3 lines listing tools we do not build by default. 

extra/vllm.binfo
extra/stable-diffusion-webui.binfo
extra/llama_cpp.binfo

(extra/corectrl.binfo requires user to install so much extra dependencies that better to list it away. And extra/tromberoil.binfo is also one of those dependencies for corectrl that many distros does not have by default)

I have also planned to add binfo files for omni debugger tools which sources amd released, just have not have time to do it.

**Comment by lamikr** [comment]
Hi, attached is the rebased the patch so that it can be applied on top of the latest changes.
Are you able to apply this on top of latest master and the push new version for review?

I modified your version only slightly:
1) you had commented the envsetup_pre.sh, I added it in this way instead:
if [[ -e "../envsetup_pre.sh" ]]; then
    source ../envsetup_pre.sh
fi
(If I want to build to another direcrory, I create that script and define there the INSTALL_DIR_PREFIX_SDK_ROOT)

2) added the git submodule changes, which I committed couple of days ago to master.

I would still like to see the helpers directory moved to build/helpers directory.
[0001-Refactor-to-make-the-babs.sh-more-manatianable.zip](https://github.com/user-attachments/files/16656470/0001-Refactor-to-make-the-babs.sh-more-manatianable.zip)

**Comment by lamikr** [comment]
Closing this as there is newer pull request for same issue.

**Pull request closed without merging**
