### PR TITLE
Void Linux support (formalizes #117)

### PR DESCRIPTION
**Pull request by jeroen-mostert**
- Add the necessary dependencies
- Include necessary patches for systems where /bin/sh is not bash (including but not limited to Void Linux)
- Fix an incompatibility in hipBLASLt between Clang 17 and GCC 13
- Take latest version of ucc (latest release is compatible with ROCm 6.x)
- Remove building the "native" architecture from ucc -- this doesn't work in headless setups. The default list should be complete.

This has gone through a full build from scratch after all the changes were made, but only on Void.  It should not impact the build on any other distros, though, as it only makes things *more* compatible.

### CODE REVIEW

**Comment by lamikr** [comment]
Found small problem, the ucc version is commented out on binfo/core/015_02_ucc_openmpi.binfo
I assume that the version should be: 985947a521d7c00e6866f032b4db4c18e5bf9e6a from Jul 25?

**Comment by jeroen-mostert** [comment]
OK, this is confusing. I originally decided to pull the latest version to see if it fixed the issue I had and based on the comment:
> v.1.2.0 does not work with rocm 6.0, use snapshot from unreleased v1.3.x branch

But 1.3.0 was released on Apr 18 and the commit is actually just the latest commit on master, so it looks like this comment is just no longer relevant and I missed the fact that the commit ID was the latest commit.

So is the intent actually to always pull a particular version of ucc and not the latest snapshot from master? If so then yes the commit needs to be reinstated (but the comment needs to go). Otherwise, any reason we don't just always pick the latest commit from master?

**Comment by lamikr** [comment]
The comment is actually wrong. I was updating some time ago the ucx and openmp to latest version because of some amd related updates and I noticed that the ucc had also some amd patches after official release. Therefore I pulled also the newest version from ucc. So the So the comment inside of binfo was wrong and was referring to some older build break.

**Comment by jeroen-mostert** [comment]
Right. So do you still want to keep the specific commit id or can we just pull the latest master? Right now that would be the same thing, but of course it won't stay that way.

**Comment by lamikr** [comment]
I prefer to always have some fixed commit-id so that the result is in theory repeatable.
If there is time to maintain later, there could be then the developer branch where the checkouts are just pointing to branches instead of fixed commits for most of the repos.

**Comment by lamikr** [comment]
I merge this now and just push second one line ucc update patch after it.

**Pull request merged**
