### PR TITLE
I created this pull request because for some reason it didn't want to update the prevoius one

### PR DESCRIPTION
**Pull request by JassonCordones**

### CODE REVIEW

**Comment by lamikr** [comment]
Hi, did not have time to go through this fully but I noticed that you did some work to add support for blist files?
And if you merge all of your patches to single patch, are you then use "git push -f" to force push the changes over the older version? It will make the reviewing of changes so much easier if there is only one commit to look at.

**Comment by lamikr** [comment]
I had time to check the patches little and I compined your latest changes again to single patch file that is attached. Nice that you added the new -ca option. That gave me idea that should we also add the -cal? (git pull, checkout and ap)

Can you try to do a following to test if you can add this patch latest attached patch as a new pull request?

git remote add upstream git@github.com:lamikr/rocm_sdk_builder.git
git fetch upsteam
git checkout upstream/master -b wip/rocm_sdk_builder_612_bg110
unzip 0001-Refactor-to-make-the-babs.sh-more-manageable.patch.zip
git am 0001-Refactor-to-make-the-babs.sh-more-manageable.patch
git push origin HEAD:wip/rocm_sdk_builder_612_bg110

And then create a pull request from that wip/rocm_sdk_builder_612_bg110 branch?
I think in that way we should be able to get clean once commit pull request that is nice to review and apply.

And if we need to do further changes, you could do following type of commands to update the pull request to newer version.

git add changed files
git commit --amend
git push -f origin HEAD:wip/rocm_sdk_builder_612_bg110

**Comment by lamikr** [comment]
func_init_and_build_single_binfo method should also be updated to handle either the build of single binfo file
or the list of binfo files which are in blist.

If the file $1 is blist it could do something like
    # read binfo/extra/ai_tools.blist
    readarray -t binfo_array < $1
else if the file $1 binfo
    binfo_array[0] = $1

Then for loop for the binfo_array from 0 to array-size-1
   func_build_single_binfo binfo_array[ii]

**Comment by lamikr** [comment]
Hi, I started working on with the blist support and if you do not mind I can apply your changes after testing them a little and then add the remaining work to support the blist as a separate patch on top of it?

**Comment by JassonCordones** [comment]
Hi, sorry for the late response. I was a bit away from the pc the last few day. I have not worked on anything after I submitted this pull request. Would you please compile a check list of what needs to be done before merging this so I can go through and work on it tomorrow? if it is not too much hassle of course

**Comment by lamikr** [comment]
That will be fine. Your changes have been very good I think the code is now in pretty good shape.
I can put here a zip file which contains 2 patches. All your changes compined to single patch
and then second patch that adds the support for blist files that you started. I have now done some testing and have not found problems but more testing is of course good to have.

In addition of blist file support, there are other small changes to improve the old functions so that instead of failing to checkout for example they will not fetch and then try to checkout again. And I removed the -fs command as the -f will do the submodule fetch now automatically for repositories which have submodules.

**Comment by lamikr** [comment]
Here are the patches.
[babs_latest_changes.zip](https://github.com/user-attachments/files/16702384/babs_latest_changes.zip)

**Comment by lamikr** [comment]
Found some errors on my own code, updated patches here:

[babs_latest_changes_v2.zip](https://github.com/user-attachments/files/16703204/babs_latest_changes_v2.zip)

**Comment by lamikr** [comment]
I have tested these changes now on 2 clean build and have not found problems on the latest version, so I think this is actually a good now to be merged. I like from the -ca command that you created, it's very useful.

If you have interest, maybe in future as a separate patches 2 things would be good additions as a a separate merge request.
 
1) Another command which works almost like: ./babs.sh -b binfo/extra/vllm.binfo now which will always do the build and install steps even if there are the builddir/vlln/.result_build and builddir/vllm/result_install files. The new command would do also the other steps (preconfig/config/build/install/postinstall) even if there are result files for those because sometimes (not always) those steps are also needed.

2) update everything to latest command which would basically do the "git pull to get latest rocm-sdk-builder version" and then the ./babs.sh -ca

**Comment by lamikr** [comment]
This pr was updated on https://github.com/lamikr/rocm_sdk_builder/pull/144 that was merged.

**Pull request closed without merging**
